/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.44
 * Generated at: 2021-03-31 08:04:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.model.service.MemberService;
import member.model.vo.Member;

public final class updatePassword_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1617176380000L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1616656753000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.service.MemberService");
    _jspx_imports_classes.add("member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("   ");

   	String msg = (String)session.getAttribute("msg");
   	if(msg != null) session.removeAttribute("msg"); //1회성 메세지
   	
   	String signupMsg = (String)session.getAttribute("signupMsg");
   	if(signupMsg != null) session.removeAttribute("signupMsg");
   	
   	String updateMsg = (String)session.getAttribute("updateMsg");
   	if(updateMsg != null) session.removeAttribute("updateMsg");
   	
   	String deleteMsg = (String)session.getAttribute("deleteMsg");
   	if(deleteMsg != null) session.removeAttribute("deleteMsg");
   	
   	String loc = (String)request.getAttribute("loc");
   	//Member loginMember = (Member)request.getAttribute("loginMember");
   	Member loginMember = (Member)session.getAttribute("loginMember");
   	//로그인 성공 시에만 객체가 담기고, 로그인 안했으면 member = null이 될 것
   			
	//사용자 쿠키처리
	String saveId = null;
	Cookie[] cookies = request.getCookies();
   	if(cookies != null){
   		for(Cookie c : cookies){
   			String name = c.getName();
   			String value = c.getValue();
   			System.out.println("coockies name, value @header.jsp=" + name + " : " + value);
   			if("saveId".equals(name)) saveId = value;
   		}
   	}
	
	
   
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Hello MVC</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/style.css\" />\n");
      out.write("<script src=\"");
      out.print( request.getContextPath() );
      out.write("/js/jquery-3.6.0.js\"></script>\n");
      out.write("<script>\n");
 if(msg != null) {
      out.write("\n");
      out.write("\talert(\"");
      out.print( msg );
      out.write("\");\n");
 } 
      out.write('\n');
      out.write('\n');
 if(loc != null){ 
      out.write("\n");
      out.write("\tlocation.href = \"");
      out.print( loc );
      out.write('"');
      out.write(';');
      out.write('\n');
 } 
      out.write('\n');
      out.write('\n');
 System.out.println("signupMsg@header=" + signupMsg); 
      out.write('\n');
 if(signupMsg != null) {
      out.write("\n");
      out.write("\talert(\"");
      out.print( signupMsg );
      out.write("\");\n");
 } 
      out.write('\n');
      out.write('\n');
 if(updateMsg != null) {
      out.write("\n");
      out.write("\talert(\"");
      out.print( updateMsg );
      out.write("\");\n");
 } 
      out.write('\n');
      out.write('\n');
 if(deleteMsg != null) {
      out.write("\n");
      out.write("\talert(\"");
      out.print( deleteMsg );
      out.write("\");\n");
 } 
      out.write("\n");
      out.write("\t$(function(){\n");
      out.write("\t\t/*\n");
      out.write("\t\t* 로그인 폼 유효성 검사\n");
      out.write("\t\t*/\n");
      out.write("\t\t$('#loginFrm').submit(function(){\n");
      out.write("\t\t\tvar $memberId = $(memberId);\n");
      out.write("\t\t\tvar $password = $(password);\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tif(/^.{4,}$/.test($memberId.val()) == false){\n");
      out.write("\t\t\t\talert(\"유효한 아이디를 입력하세요.\");\n");
      out.write("\t\t\t\t$memberId.select();\n");
      out.write("\t\t\t\treturn false;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\tif(/^.{4,}$/.test($password.val()) == false){\n");
      out.write("\t\t\t\talert(\"유효한 비밀번호를 입력하세요.\");\n");
      out.write("\t\t\t\t$password.select();\n");
      out.write("\t\t\t\treturn false;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t});\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t/* \n");
      out.write("\t\t회원가입 폼 제출전 적절한 유효성 검사를 실시할 것.\n");
      out.write("\t\t<memberEnroll.jsp에서 처리>\n");
      out.write("\t\t*/\n");
      out.write("\t/* \t$('[name=\"memberEnrollFrm\"]').submit(function(){\n");
      out.write("\t\t\t//id 4자이상\n");
      out.write("\t\t\tvar $memberId_ = $(\"#memberId_\");\n");
      out.write("\t\t\tif(/^.{4,}$/.test($memberId_.val()) == false){\n");
      out.write("\t\t\t\talert(\"아이디는 4자 이상이어야 합니다.\");\n");
      out.write("\t\t\t\t$memberId_.select();\n");
      out.write("\t\t\t\treturn false;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t//전화번호 -없이\n");
      out.write("\t\t\tvar $phone = $(\"#phone\");\n");
      out.write("\t\t\tif(/^[0-9]{10,11}/.test($phone.val()) == false){\n");
      out.write("\t\t\t\talert(\"전화번호는 숫자로만 입력해주세요.\");\n");
      out.write("\t\t\t\t$phone.select();\n");
      out.write("\t\t\t\treturn false;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t\n");
      out.write("\t\t}); */\n");
      out.write("\t\t\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<div id=\"container\">\n");
      out.write("\t\t<header>\n");
      out.write("\t\t\t<h1>Hello MVC</h1>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\t<div class=\"login-container\">\n");
      out.write("\t\t\t\t");
 if(loginMember == null) { 
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<!-- 로그인폼 시작 -->\n");
      out.write("\t\t\t\t\t<form id=\"loginFrm\" action=\"");
      out.print(request.getContextPath() );
      out.write("/member/login\" method=\"POST\">\n");
      out.write("\t\t\t\t\t\t<table>\n");
      out.write("\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"memberId\" id=\"memberId\" placeholder=\"아이디\" tabindex=\"1\" value=\"");
      out.print( saveId != null ? saveId : "" );
      out.write("\"></td>\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"submit\" value=\"로그인\" tabindex=\"3\"></td>\n");
      out.write("\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"password\" name=\"password\" id=\"password\"\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"비밀번호\" tabindex=\"2\"></td>\n");
      out.write("\t\t\t\t\t\t\t\t<td></td>\n");
      out.write("\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"2\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"saveId\" id=\"saveId\" ");
      out.print( saveId != null? "checked" : "" );
      out.write("/>\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"saveId\">아이디저장</label>&nbsp;&nbsp;\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"button\" value=\"회원가입\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/member/memberEnroll'\">\n");
      out.write("\t\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t</table>\n");
      out.write("\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t\t<!-- 로그인폼 끝-->\n");
      out.write("\t\t\t\t\t");
 } else{ 
      out.write("\n");
      out.write("\t\t\t\t\t\t");
      out.write("\n");
      out.write("\t\t\t\t\t\t<table id=\"login\">\n");
      out.write("\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print( loginMember.getMemberName() );
      out.write(" 님, 안녕하세요.</td>\n");
      out.write("\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"button\" value=\"내정보보기\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/member/memberView';\" />\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"button\" value=\"로그아웃\"\n");
      out.write("\t\t\t\t\t\t\t\t\tonclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/member/logout';\" />\n");
      out.write("\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t</table>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t");
 } 
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<!-- 메인메뉴 시작 -->\n");
      out.write("\t\t\t\t<nav>\n");
      out.write("\t\t\t\t\t<ul class=\"main-nav\">\n");
      out.write("\t\t\t\t\t\t<li class=\"home\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("\">Home</a></li>\n");
      out.write("\t\t\t\t\t\t<li class=\"notice\"><a href=\"#\">공지사항</a></li>\n");
      out.write("\t\t\t\t\t\t<li class=\"board\"><a href=\"#\">게시판</a></li>\n");
      out.write("\t\t\t\t\t\t");
      out.write("\n");
      out.write("\t\t\t\t\t\t");
 if(loginMember!=null && MemberService.ADMIN_ROLE.equals(loginMember.getMemberRole())){ 
      out.write("\n");
      out.write("\t\t\t\t\t\t<li class=\"members\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("/admin/memberlist\">회원관리</a></li>\n");
      out.write("\t\t\t\t\t\t");
 } 
      out.write("\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</nav>\n");
      out.write("\t\t\t\t<!-- 메인메뉴 끝-->\n");
      out.write("\t\t</header>\n");
      out.write("\t\t\n");
      out.write("\t\t<section id=\"content\">");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<section id=enroll-container>\r\n");
      out.write("\t\t<h2>비밀번호 변경</h2>\r\n");
      out.write("\t\t<form \r\n");
      out.write("\t\t\tname=\"updatePwdFrm\" \r\n");
      out.write("\t\t\taction=\"");
      out.print(request.getContextPath());
      out.write("/member/updatePassword\" \r\n");
      out.write("\t\t\tmethod=\"post\" >\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>현재 비밀번호</th>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"password\" name=\"password\" id=\"password\" required></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>변경할 비밀번호</th>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"password\" name=\"newPassword\" id=\"newPassword\" required>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>비밀번호 확인</th>\r\n");
      out.write("\t\t\t\t\t<td>\t\r\n");
      out.write("\t\t\t\t\t\t<input type=\"password\" name=\"passwordCheck\" id=\"passwordCheck\" required><br>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"2\" style=\"text-align: center;\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\"변경\" />\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t//폼제출 유효성검사\r\n");
      out.write("\t$(\"[name=updatePwdFrm]\").submit(function(){\r\n");
      out.write("\t\tvar $oldPassword = $(\"#password\");\r\n");
      out.write("\t\tvar $newPassword = $(\"#newPassword\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(!passwordValidate()){\r\n");
      out.write("\t\t\talert(\"입력한 비밀번호가 일치하지 않습니다.\");\r\n");
      out.write("\t\t\t$newPassword.select();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif($oldPassword.val() == $newPassword.val()){\r\n");
      out.write("\t\t\talert(\"기존비밀번호와 신규비밀번호는 같을 수 없습니다.\");\r\n");
      out.write("\t\t\t$oldPassword.select();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\treturn true;\t\r\n");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t//신규비밀번호 일치 검사\r\n");
      out.write("\t$(\"#passwordCheck\").blur(passwordValidate);\r\n");
      out.write("\r\n");
      out.write("\tfunction passwordValidate(){\r\n");
      out.write("\t\tvar $newPassword = $(\"#newPassword\");\r\n");
      out.write("\t\tvar $newPasswordCheck = $(\"#passwordCheck\");\r\n");
      out.write("\t\tif($newPassword.val() != $newPasswordCheck.val()){\r\n");
      out.write("\t\t\talert(\"입력한 비밀번호가 일치하지 않습니다.\");\r\n");
      out.write("\t\t\t$newPassword.select();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn true;\t\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\n");
      out.write("\t\t</section>\n");
      out.write("\n");
      out.write("\t\t<footer>\n");
      out.write("\t\t\t<p>&lt;Copyright 1998-2021 <strong>KH정보교육원</strong>. All rights reserved.&gt;</p>\n");
      out.write("\t\t</footer>\n");
      out.write("\t</div>\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
